### ISSUE TITLE
Error: need curl or pycurl to perform downloads

### ISSUE THREAD

**Issue by funnymomo** [grycap/scar#299]
Did fresh build from the Dockerfile in the root of the git.
Using Docker on Windows on Windows 10 (though shouldn't matter).

Then ran : scar init -n scar-cowsay -i grycap/cowsay and got the following error.

scar@b32a7c210e24:~$ scar init -n scar-cowsay -i grycap/cowsay
Error: need curl or pycurl to perform downloads
Traceback (most recent call last):
  File "udocker.py", line 7157, in <module>
  File "udocker.py", line 7096, in __init__
  File "udocker.py", line 5963, in __init__
  File "udocker.py", line 5114, in __init__
  File "udocker.py", line 4776, in __init__
  File "udocker.py", line 4788, in _select_implementation
NameError: need curl or pycurl
[25] Failed to execute script udocker
There was an unmanaged exception in prepare_lambda_code

My suspicion is that somehow the curl binary that's being added here is not being read and that why udocker.py throws an error. Spent couple of hours trying to figure out but no luck.
Please help.

>>> from the Dockerfile
RUN pyinstaller --onefile \
  --add-binary="/usr/bin/curl:src/bin" \
  -n udockerb \
  udocker.py

P.S.
The main Docker file is at root is pointing to a older version of udocker, it should point to 1.1.3.

--add-data="src/providers/aws/cloud/lambda/udocker/udocker-1.1.3.tar.gz:src/providers/aws/cloud/lambda/udocker" \

**Comment by alpegon** [comment]
Hi,

I fixed the issue in the PR #300.
The problem was caused because I forgot to update the udocker code when I updated from the previous version.
I've also updated the Dockerfile to include the latest version. Thanks for pointing it out.

Cheers

**Comment by funnymomo** [comment]
Hi,

Thanks for doing this...I tried again to build the Docker file at the root of this repo and still get the same error. Looks like you initially added the curl bin and then removed it in favor of pycurl. 
To be double sure, I cloned this to completely new directory.

I mean the Docker image builds all right but the moment I run 
scar init -n scar-cowsay -i grycap/cowsay
it fails for lack of curl.


scar@721e0db230b4:~$ ls /home/scar/.scar
scar.cfg  scar.cfg_o2  scar.cfg_old
scar@721e0db230b4:~$ scar init -n scar-cowsay -i grycap/cowsay
Error: need curl or pycurl to perform downloads
Traceback (most recent call last):
  File "udocker.py", line 7157, in <module>
  File "udocker.py", line 7096, in __init__
  File "udocker.py", line 5963, in __init__
  File "udocker.py", line 5114, in __init__
  File "udocker.py", line 4776, in __init__
  File "udocker.py", line 4788, in _select_implementation
NameError: need curl or pycurl
[26] Failed to execute script udocker
There was an unmanaged exception in prepare_lambda_code
